---
title: "recommeder_systems"
author: "Yashvin Jagarlamudi"
date: "11/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(knitr)
library(recommenderlab)


```


```{r}

table_f<-fread("spotify_current_popularity.csv")
memory.limit(size=56000)
music_tibble<-as_data_frame(table_f)
head(music_tibble)

```

```{r}

music_tibble <- music_tibble %>%
  mutate(ratings=case_when(
    current_popularity >= 0 & salary < 10 ~ 0,
    current_popularity >= 10 & salary < 19 ~ 1,
    current_popularity >= 20 & salary < 29 ~ 2,
    current_popularity >= 30 & salary < 39 ~ 3,
    current_popularity >= 40 & salary < 49 ~ 4,
    current_popularity >= 50 & salary < 59 ~ 5,
    current_popularity >= 60 & salary < 69 ~ 6,
    current_popularity >= 70 & salary < 79 ~ 7,
    current_popularity >= 80 & salary < 89 ~ 9,
    current_popularity >= 90 & salary < 99 ~ 9,
    current_popularity == 100 ~ 10,
    TRUE                             ~ "NA"
  ))
```


```{r}
music_ratings<-music_tibble %>%
  group_by(ratings)%>%
  count()


vector_ratings<-as.vector(music_ratings)
kable(table(vector_ratings), caption="Rating frequency")

```


```{r}
vector_ratings = vector_ratings[vector_ratings != 0]
hist(vector_ratings, main="Histogram of Ratings", xlab="Rating Value")


```



```{r}

percent_train = 0.8
#min(rowCounts(ratings.n))
items_to_keep = 15        # items to use for each user
rating_threshold = 3      # good rating implies >=3
n_eval = 1                # number of times to run eval

eval_sets = evaluationScheme(data = ratings, method = "split",
                             train = percent_train, given = items_to_keep,
                             goodRating = rating_threshold, k = n_eval)
eval_sets

```



```{r}

eval_recommender = Recommender(data = getData(eval_sets, "train"),
                               method = "UBCF", parameter = NULL)
items_to_recommend = 10
eval_prediction = predict(object = eval_recommender,
                          newdata = getData(eval_sets, "known"),
                          n = items_to_recommend,
                          type = "ratings")
eval_accuracy = calcPredictionAccuracy(x = eval_prediction,
                                       data = getData(eval_sets, "unknown"),
                                       byUser = TRUE)
head(eval_accuracy)


```




```{r}

eval_recommender = Recommender(data = getData(eval_sets, "train"),
                               method = "IBCF", parameter = NULL)
items_to_recommend = 10
eval_prediction = predict(object = eval_recommender,
                          newdata = getData(eval_sets, "known"),
                          n = items_to_recommend,
                          type = "ratings")
eval_accuracy = calcPredictionAccuracy(x = eval_prediction,
                                       data = getData(eval_sets, "unknown"),
                                       byUser = TRUE)
head(eval_accuracy)

```



```{r}

models_to_evaluate = list(IBCF_cos = list(name = "IBCF", param = list(method = "cosine")),
                          IBCF_cor = list(name = "IBCF", param = list(method = "pearson")),
                          UBCF_cos = list(name = "UBCF", param = list(method = "cosine")),
                          UBCF_cor = list(name = "UBCF", param = list(method = "pearson")),
                          random = list(name = "RANDOM", param=NULL))

n_recommendations = c(1, 3, 5, 10, 15, 20)
results = evaluate(x = eval_sets, method = models_to_evaluate, n = n_recommendations)

```



```{r}
plot(results, y = "ROC", annotate = 1, legend="topleft")
title("ROC Curve")


```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```



```{r}



```


